-- Database schema for knittingdb
CREATE DATABASE IF NOT EXISTS `knittingdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `knittingdb`;

-- Table: knit_card
CREATE TABLE IF NOT EXISTS `knit_card` (
  `KCID` INT(11) NOT NULL AUTO_INCREMENT,
  `KPTID` INT(11) NOT NULL,
  `CARD_DATE` DATE DEFAULT NULL,
  `MCNO` VARCHAR(50) DEFAULT NULL,
  `FINISH_DIA` VARCHAR(50) DEFAULT NULL,
  `FINISH_GSM` VARCHAR(50) DEFAULT NULL,
  `GREY_GSM` VARCHAR(50) DEFAULT NULL,
  `SL_VDQ` DECIMAL(10,2) DEFAULT 0.00,
  `OPEN_TUBE` VARCHAR(20) DEFAULT 'O',
  `BUYER` VARCHAR(100) DEFAULT NULL,
  `SUPPLIER` VARCHAR(100) DEFAULT NULL,
  `BOOKING` VARCHAR(100) DEFAULT NULL,
  `SONO` VARCHAR(100) DEFAULT NULL,
  `STYLE` VARCHAR(100) DEFAULT NULL,
  `FABRICS_TYPE` TEXT DEFAULT NULL,
  `YARN_TYPE` TEXT DEFAULT NULL,
  `YARN_COUNT` VARCHAR(100) DEFAULT NULL,
  `LOT_NO` VARCHAR(100) DEFAULT NULL,
  `KNIT_M_DESCRIPTION` TEXT DEFAULT NULL,
  `REQ_QTY` DECIMAL(10,2) DEFAULT 0.00,
  `PREPARED_BY` VARCHAR(100) DEFAULT NULL,
  `AUTHORISED_BY` VARCHAR(100) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KCID`),
  KEY `KPTID` (`KPTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: knit_card_production
CREATE TABLE IF NOT EXISTS `knit_card_production` (
  `KCPID` INT(11) NOT NULL AUTO_INCREMENT,
  `KCID` INT(11) NOT NULL,
  `LOG_DATE` DATE DEFAULT NULL,
  `A_SHIFT_QTY` DECIMAL(10,2) DEFAULT 0.00,
  `B_SHIFT_QTY` DECIMAL(10,2) DEFAULT 0.00,
  `C_SHIFT_QTY` DECIMAL(10,2) DEFAULT 0.00,
  `PRODUCTION_QTY` DECIMAL(10,2) DEFAULT 0.00,
  `CUM_TOTAL` DECIMAL(10,2) DEFAULT 0.00,
  `BALANCE` DECIMAL(10,2) DEFAULT 0.00,
  `OPERATOR_A` VARCHAR(100) DEFAULT NULL,
  `OPERATOR_B` VARCHAR(100) DEFAULT NULL,
  `OPERATOR_C` VARCHAR(100) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KCPID`),
  KEY `KCID` (`KCID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: knitting_production
CREATE TABLE IF NOT EXISTS `knitting_production` (
  `PID` INT(11) NOT NULL AUTO_INCREMENT,
  `BUDAT` DATE DEFAULT NULL,
  `ROLL` VARCHAR(100) DEFAULT NULL,
  `BOOKING_NO` VARCHAR(100) DEFAULT NULL,
  `SONO` VARCHAR(100) DEFAULT NULL,
  `MCNO` VARCHAR(50) DEFAULT NULL,
  `MC_DIA` VARCHAR(50) DEFAULT NULL,
  `BUYER` VARCHAR(100) DEFAULT NULL,
  `STYLE` VARCHAR(100) DEFAULT NULL,
  `YARN_TYPE` TEXT DEFAULT NULL,
  `YARN_COUNT` VARCHAR(100) DEFAULT NULL,
  `FABRICS_TYPE` TEXT DEFAULT NULL,
  `FINISH_GSM` VARCHAR(50) DEFAULT NULL,
  `FINISH_DIA` VARCHAR(50) DEFAULT NULL,
  `OPEN_TUBE` VARCHAR(20) DEFAULT NULL,
  `COLOR` VARCHAR(100) DEFAULT NULL,
  `SL_VDQ` DECIMAL(10,2) DEFAULT 0.00,
  `OQTY` DECIMAL(10,2) DEFAULT 0.00,
  `RQTY` DECIMAL(10,2) DEFAULT 0.00,
  `UQTY` DECIMAL(10,2) DEFAULT 0.00,
  `LOT_NO` VARCHAR(100) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PID`),
  KEY `ROLL` (`ROLL`),
  KEY `BOOKING_NO` (`BOOKING_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: knitting_program
CREATE TABLE IF NOT EXISTS `knitting_program` (
  `KPTID` INT(11) NOT NULL AUTO_INCREMENT,
  `MAIN_TID` BIGINT(20) NOT NULL DEFAULT 1000000000,
  `SUB_TID` BIGINT(20) NOT NULL DEFAULT 2000000000,
  `BOOKING` VARCHAR(100) DEFAULT NULL,
  `SONO` VARCHAR(100) DEFAULT NULL,
  `STYLE` VARCHAR(100) DEFAULT NULL,
  `BUYER` VARCHAR(100) DEFAULT NULL,
  `SUPPLIER` VARCHAR(100) DEFAULT NULL,
  `KNIT_M_DESCRIPTION` TEXT DEFAULT NULL,
  `MCNO` VARCHAR(50) DEFAULT NULL,
  `MC_DIA` VARCHAR(50) DEFAULT NULL,
  `QTY` DECIMAL(10,2) DEFAULT 0.00,
  `SHIFT` VARCHAR(20) DEFAULT NULL,
  `YARN_TYPE` TEXT DEFAULT NULL,
  `YARN_COUNT` VARCHAR(100) DEFAULT NULL,
  `FABRICS_TYPE` TEXT DEFAULT NULL,
  `FINISH_GSM` VARCHAR(50) DEFAULT NULL,
  `FINISH_DIA` VARCHAR(50) DEFAULT NULL,
  `OPEN_TUBE` VARCHAR(20) DEFAULT NULL,
  `SL_VDQ` DECIMAL(10,2) DEFAULT 0.00,
  `LOT_NO` VARCHAR(100) DEFAULT NULL,
  `KNIT_MATERIAL_CODE` VARCHAR(100) DEFAULT NULL,
  `COLOR` VARCHAR(100) DEFAULT NULL,
  `CARD_GENERATED` TINYINT(1) NOT NULL DEFAULT 0,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`KPTID`),
  KEY `BOOKING` (`BOOKING`),
  KEY `MCNO` (`MCNO`),
  KEY `MAIN_TID` (`MAIN_TID`),
  KEY `SUB_TID` (`SUB_TID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ensure CARD_GENERATED column exists on knitting_program
ALTER TABLE `knitting_program` ADD COLUMN IF NOT EXISTS `CARD_GENERATED` TINYINT(1) NOT NULL DEFAULT 0;
